# Generated by Django 4.2.29 on 2026-04-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='score',
            field=models.IntegerField(default=100),
        ),
    ]
